/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EdgeScore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EdgeScore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EdgeScore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkPredJavaJNI.delete_EdgeScore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI(String value) {
    LinkPredJavaJNI.EdgeScore_i_set(swigCPtr, this, value);
  }

  public String getI() {
    return LinkPredJavaJNI.EdgeScore_i_get(swigCPtr, this);
  }

  public void setJ(String value) {
    LinkPredJavaJNI.EdgeScore_j_set(swigCPtr, this, value);
  }

  public String getJ() {
    return LinkPredJavaJNI.EdgeScore_j_get(swigCPtr, this);
  }

  public void setScore(double value) {
    LinkPredJavaJNI.EdgeScore_score_set(swigCPtr, this, value);
  }

  public double getScore() {
    return LinkPredJavaJNI.EdgeScore_score_get(swigCPtr, this);
  }

  public EdgeScore() {
    this(LinkPredJavaJNI.new_EdgeScore(), true);
  }

}
