/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EdgeScoreVec extends java.util.AbstractList<EdgeScore> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EdgeScoreVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EdgeScoreVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkPredJavaJNI.delete_EdgeScoreVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EdgeScoreVec(EdgeScore[] initialElements) {
    this();
    reserve(initialElements.length);

    for (EdgeScore element : initialElements) {
      add(element);
    }
  }

  public EdgeScoreVec(Iterable<EdgeScore> initialElements) {
    this();
    for (EdgeScore element : initialElements) {
      add(element);
    }
  }

  public EdgeScore get(int index) {
    return doGet(index);
  }

  public EdgeScore set(int index, EdgeScore e) {
    return doSet(index, e);
  }

  public boolean add(EdgeScore e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, EdgeScore e) {
    modCount++;
    doAdd(index, e);
  }

  public EdgeScore remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public EdgeScoreVec() {
    this(LinkPredJavaJNI.new_EdgeScoreVec__SWIG_0(), true);
  }

  public EdgeScoreVec(EdgeScoreVec other) {
    this(LinkPredJavaJNI.new_EdgeScoreVec__SWIG_1(EdgeScoreVec.getCPtr(other), other), true);
  }

  public long capacity() {
    return LinkPredJavaJNI.EdgeScoreVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    LinkPredJavaJNI.EdgeScoreVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return LinkPredJavaJNI.EdgeScoreVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    LinkPredJavaJNI.EdgeScoreVec_clear(swigCPtr, this);
  }

  public EdgeScoreVec(int count, EdgeScore value) {
    this(LinkPredJavaJNI.new_EdgeScoreVec__SWIG_2(count, EdgeScore.getCPtr(value), value), true);
  }

  private int doSize() {
    return LinkPredJavaJNI.EdgeScoreVec_doSize(swigCPtr, this);
  }

  private void doAdd(EdgeScore x) {
    LinkPredJavaJNI.EdgeScoreVec_doAdd__SWIG_0(swigCPtr, this, EdgeScore.getCPtr(x), x);
  }

  private void doAdd(int index, EdgeScore x) {
    LinkPredJavaJNI.EdgeScoreVec_doAdd__SWIG_1(swigCPtr, this, index, EdgeScore.getCPtr(x), x);
  }

  private EdgeScore doRemove(int index) {
    return new EdgeScore(LinkPredJavaJNI.EdgeScoreVec_doRemove(swigCPtr, this, index), true);
  }

  private EdgeScore doGet(int index) {
    return new EdgeScore(LinkPredJavaJNI.EdgeScoreVec_doGet(swigCPtr, this, index), false);
  }

  private EdgeScore doSet(int index, EdgeScore val) {
    return new EdgeScore(LinkPredJavaJNI.EdgeScoreVec_doSet(swigCPtr, this, index, EdgeScore.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    LinkPredJavaJNI.EdgeScoreVec_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
