/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EdgeScoreByIDVec extends java.util.AbstractList<EdgeScoreByID> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EdgeScoreByIDVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EdgeScoreByIDVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkPredJavaJNI.delete_EdgeScoreByIDVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EdgeScoreByIDVec(EdgeScoreByID[] initialElements) {
    this();
    reserve(initialElements.length);

    for (EdgeScoreByID element : initialElements) {
      add(element);
    }
  }

  public EdgeScoreByIDVec(Iterable<EdgeScoreByID> initialElements) {
    this();
    for (EdgeScoreByID element : initialElements) {
      add(element);
    }
  }

  public EdgeScoreByID get(int index) {
    return doGet(index);
  }

  public EdgeScoreByID set(int index, EdgeScoreByID e) {
    return doSet(index, e);
  }

  public boolean add(EdgeScoreByID e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, EdgeScoreByID e) {
    modCount++;
    doAdd(index, e);
  }

  public EdgeScoreByID remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public EdgeScoreByIDVec() {
    this(LinkPredJavaJNI.new_EdgeScoreByIDVec__SWIG_0(), true);
  }

  public EdgeScoreByIDVec(EdgeScoreByIDVec other) {
    this(LinkPredJavaJNI.new_EdgeScoreByIDVec__SWIG_1(EdgeScoreByIDVec.getCPtr(other), other), true);
  }

  public long capacity() {
    return LinkPredJavaJNI.EdgeScoreByIDVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    LinkPredJavaJNI.EdgeScoreByIDVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return LinkPredJavaJNI.EdgeScoreByIDVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    LinkPredJavaJNI.EdgeScoreByIDVec_clear(swigCPtr, this);
  }

  public EdgeScoreByIDVec(int count, EdgeScoreByID value) {
    this(LinkPredJavaJNI.new_EdgeScoreByIDVec__SWIG_2(count, EdgeScoreByID.getCPtr(value), value), true);
  }

  private int doSize() {
    return LinkPredJavaJNI.EdgeScoreByIDVec_doSize(swigCPtr, this);
  }

  private void doAdd(EdgeScoreByID x) {
    LinkPredJavaJNI.EdgeScoreByIDVec_doAdd__SWIG_0(swigCPtr, this, EdgeScoreByID.getCPtr(x), x);
  }

  private void doAdd(int index, EdgeScoreByID x) {
    LinkPredJavaJNI.EdgeScoreByIDVec_doAdd__SWIG_1(swigCPtr, this, index, EdgeScoreByID.getCPtr(x), x);
  }

  private EdgeScoreByID doRemove(int index) {
    return new EdgeScoreByID(LinkPredJavaJNI.EdgeScoreByIDVec_doRemove(swigCPtr, this, index), true);
  }

  private EdgeScoreByID doGet(int index) {
    return new EdgeScoreByID(LinkPredJavaJNI.EdgeScoreByIDVec_doGet(swigCPtr, this, index), false);
  }

  private EdgeScoreByID doSet(int index, EdgeScoreByID val) {
    return new EdgeScoreByID(LinkPredJavaJNI.EdgeScoreByIDVec_doSet(swigCPtr, this, index, EdgeScoreByID.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    LinkPredJavaJNI.EdgeScoreByIDVec_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
