/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Evaluator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Evaluator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Evaluator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkPredJavaJNI.delete_Evaluator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Evaluator() {
    this(LinkPredJavaJNI.new_Evaluator__SWIG_0(), true);
  }

  public Evaluator(Evaluator that) {
    this(LinkPredJavaJNI.new_Evaluator__SWIG_1(Evaluator.getCPtr(that), that), true);
  }

  public void addADA(String name) {
    LinkPredJavaJNI.Evaluator_addADA__SWIG_0(swigCPtr, this, name);
  }

  public void addADA() {
    LinkPredJavaJNI.Evaluator_addADA__SWIG_1(swigCPtr, this);
  }

  public void addCNE(String name) {
    LinkPredJavaJNI.Evaluator_addCNE__SWIG_0(swigCPtr, this, name);
  }

  public void addCNE() {
    LinkPredJavaJNI.Evaluator_addCNE__SWIG_1(swigCPtr, this);
  }

  public void addCRA(String name) {
    LinkPredJavaJNI.Evaluator_addCRA__SWIG_0(swigCPtr, this, name);
  }

  public void addCRA() {
    LinkPredJavaJNI.Evaluator_addCRA__SWIG_1(swigCPtr, this);
  }

  public void addECL(String name, String encoderName, String classifierName, int dim, double posRatio, double negRatio, int seed) {
    LinkPredJavaJNI.Evaluator_addECL__SWIG_0(swigCPtr, this, name, encoderName, classifierName, dim, posRatio, negRatio, seed);
  }

  public void addECL(String name, String encoderName, String classifierName, int dim, double posRatio, double negRatio) {
    LinkPredJavaJNI.Evaluator_addECL__SWIG_1(swigCPtr, this, name, encoderName, classifierName, dim, posRatio, negRatio);
  }

  public void addECL(String name, String encoderName, String classifierName, int dim, double posRatio) {
    LinkPredJavaJNI.Evaluator_addECL__SWIG_2(swigCPtr, this, name, encoderName, classifierName, dim, posRatio);
  }

  public void addECL(String name, String encoderName, String classifierName, int dim) {
    LinkPredJavaJNI.Evaluator_addECL__SWIG_3(swigCPtr, this, name, encoderName, classifierName, dim);
  }

  public void addECL(String name, String encoderName, String classifierName) {
    LinkPredJavaJNI.Evaluator_addECL__SWIG_4(swigCPtr, this, name, encoderName, classifierName);
  }

  public void addECL(String name, String encoderName) {
    LinkPredJavaJNI.Evaluator_addECL__SWIG_5(swigCPtr, this, name, encoderName);
  }

  public void addECL(String name) {
    LinkPredJavaJNI.Evaluator_addECL__SWIG_6(swigCPtr, this, name);
  }

  public void addECL() {
    LinkPredJavaJNI.Evaluator_addECL__SWIG_7(swigCPtr, this);
  }

  public void addESM(String name, String encoderName, String simMeasureName, int dim, int seed) {
    LinkPredJavaJNI.Evaluator_addESM__SWIG_0(swigCPtr, this, name, encoderName, simMeasureName, dim, seed);
  }

  public void addESM(String name, String encoderName, String simMeasureName, int dim) {
    LinkPredJavaJNI.Evaluator_addESM__SWIG_1(swigCPtr, this, name, encoderName, simMeasureName, dim);
  }

  public void addESM(String name, String encoderName, String simMeasureName) {
    LinkPredJavaJNI.Evaluator_addESM__SWIG_2(swigCPtr, this, name, encoderName, simMeasureName);
  }

  public void addESM(String name, String encoderName) {
    LinkPredJavaJNI.Evaluator_addESM__SWIG_3(swigCPtr, this, name, encoderName);
  }

  public void addESM(String name) {
    LinkPredJavaJNI.Evaluator_addESM__SWIG_4(swigCPtr, this, name);
  }

  public void addESM() {
    LinkPredJavaJNI.Evaluator_addESM__SWIG_5(swigCPtr, this);
  }

  public void addFBM(String name, int maxIter, int seed) {
    LinkPredJavaJNI.Evaluator_addFBM__SWIG_0(swigCPtr, this, name, maxIter, seed);
  }

  public void addFBM(String name, int maxIter) {
    LinkPredJavaJNI.Evaluator_addFBM__SWIG_1(swigCPtr, this, name, maxIter);
  }

  public void addFBM(String name) {
    LinkPredJavaJNI.Evaluator_addFBM__SWIG_2(swigCPtr, this, name);
  }

  public void addFBM() {
    LinkPredJavaJNI.Evaluator_addFBM__SWIG_3(swigCPtr, this);
  }

  public void addHDI(String name) {
    LinkPredJavaJNI.Evaluator_addHDI__SWIG_0(swigCPtr, this, name);
  }

  public void addHDI() {
    LinkPredJavaJNI.Evaluator_addHDI__SWIG_1(swigCPtr, this);
  }

  public void addHPI(String name) {
    LinkPredJavaJNI.Evaluator_addHPI__SWIG_0(swigCPtr, this, name);
  }

  public void addHPI() {
    LinkPredJavaJNI.Evaluator_addHPI__SWIG_1(swigCPtr, this);
  }

  public void addHRG(String name, int nbBeans, int nbSamples, int seed) {
    LinkPredJavaJNI.Evaluator_addHRG__SWIG_0(swigCPtr, this, name, nbBeans, nbSamples, seed);
  }

  public void addHRG(String name, int nbBeans, int nbSamples) {
    LinkPredJavaJNI.Evaluator_addHRG__SWIG_1(swigCPtr, this, name, nbBeans, nbSamples);
  }

  public void addHRG(String name, int nbBeans) {
    LinkPredJavaJNI.Evaluator_addHRG__SWIG_2(swigCPtr, this, name, nbBeans);
  }

  public void addHRG(String name) {
    LinkPredJavaJNI.Evaluator_addHRG__SWIG_3(swigCPtr, this, name);
  }

  public void addHRG() {
    LinkPredJavaJNI.Evaluator_addHRG__SWIG_4(swigCPtr, this);
  }

  public void addHYP(String name, double m, double L, double gamma, double zeta, double T, int seed) {
    LinkPredJavaJNI.Evaluator_addHYP__SWIG_0(swigCPtr, this, name, m, L, gamma, zeta, T, seed);
  }

  public void addHYP(String name, double m, double L, double gamma, double zeta, double T) {
    LinkPredJavaJNI.Evaluator_addHYP__SWIG_1(swigCPtr, this, name, m, L, gamma, zeta, T);
  }

  public void addHYP(String name, double m, double L, double gamma, double zeta) {
    LinkPredJavaJNI.Evaluator_addHYP__SWIG_2(swigCPtr, this, name, m, L, gamma, zeta);
  }

  public void addHYP(String name, double m, double L, double gamma) {
    LinkPredJavaJNI.Evaluator_addHYP__SWIG_3(swigCPtr, this, name, m, L, gamma);
  }

  public void addHYP(String name, double m, double L) {
    LinkPredJavaJNI.Evaluator_addHYP__SWIG_4(swigCPtr, this, name, m, L);
  }

  public void addHYP(String name, double m) {
    LinkPredJavaJNI.Evaluator_addHYP__SWIG_5(swigCPtr, this, name, m);
  }

  public void addHYP(String name) {
    LinkPredJavaJNI.Evaluator_addHYP__SWIG_6(swigCPtr, this, name);
  }

  public void addHYP() {
    LinkPredJavaJNI.Evaluator_addHYP__SWIG_7(swigCPtr, this);
  }

  public void addJID(String name) {
    LinkPredJavaJNI.Evaluator_addJID__SWIG_0(swigCPtr, this, name);
  }

  public void addJID() {
    LinkPredJavaJNI.Evaluator_addJID__SWIG_1(swigCPtr, this);
  }

  public void addKAB(String name, int horizLim) {
    LinkPredJavaJNI.Evaluator_addKAB__SWIG_0(swigCPtr, this, name, horizLim);
  }

  public void addKAB(String name) {
    LinkPredJavaJNI.Evaluator_addKAB__SWIG_1(swigCPtr, this, name);
  }

  public void addKAB() {
    LinkPredJavaJNI.Evaluator_addKAB__SWIG_2(swigCPtr, this);
  }

  public void addLCP(String name, double epsilon) {
    LinkPredJavaJNI.Evaluator_addLCP__SWIG_0(swigCPtr, this, name, epsilon);
  }

  public void addLCP(String name) {
    LinkPredJavaJNI.Evaluator_addLCP__SWIG_1(swigCPtr, this, name);
  }

  public void addLCP() {
    LinkPredJavaJNI.Evaluator_addLCP__SWIG_2(swigCPtr, this);
  }

  public void addLHN(String name) {
    LinkPredJavaJNI.Evaluator_addLHN__SWIG_0(swigCPtr, this, name);
  }

  public void addLHN() {
    LinkPredJavaJNI.Evaluator_addLHN__SWIG_1(swigCPtr, this);
  }

  public void addPAT(String name) {
    LinkPredJavaJNI.Evaluator_addPAT__SWIG_0(swigCPtr, this, name);
  }

  public void addPAT() {
    LinkPredJavaJNI.Evaluator_addPAT__SWIG_1(swigCPtr, this);
  }

  public void addPST(String name, String fileName) {
    LinkPredJavaJNI.Evaluator_addPST__SWIG_0(swigCPtr, this, name, fileName);
  }

  public void addPST(String name) {
    LinkPredJavaJNI.Evaluator_addPST__SWIG_1(swigCPtr, this, name);
  }

  public void addPST() {
    LinkPredJavaJNI.Evaluator_addPST__SWIG_2(swigCPtr, this);
  }

  public void addRAL(String name) {
    LinkPredJavaJNI.Evaluator_addRAL__SWIG_0(swigCPtr, this, name);
  }

  public void addRAL() {
    LinkPredJavaJNI.Evaluator_addRAL__SWIG_1(swigCPtr, this);
  }

  public void addRND(String name, int seed) {
    LinkPredJavaJNI.Evaluator_addRND__SWIG_0(swigCPtr, this, name, seed);
  }

  public void addRND(String name) {
    LinkPredJavaJNI.Evaluator_addRND__SWIG_1(swigCPtr, this, name);
  }

  public void addRND() {
    LinkPredJavaJNI.Evaluator_addRND__SWIG_2(swigCPtr, this);
  }

  public void addSAI(String name) {
    LinkPredJavaJNI.Evaluator_addSAI__SWIG_0(swigCPtr, this, name);
  }

  public void addSAI() {
    LinkPredJavaJNI.Evaluator_addSAI__SWIG_1(swigCPtr, this);
  }

  public void addSBM(String name, int maxIter, int seed) {
    LinkPredJavaJNI.Evaluator_addSBM__SWIG_0(swigCPtr, this, name, maxIter, seed);
  }

  public void addSBM(String name, int maxIter) {
    LinkPredJavaJNI.Evaluator_addSBM__SWIG_1(swigCPtr, this, name, maxIter);
  }

  public void addSBM(String name) {
    LinkPredJavaJNI.Evaluator_addSBM__SWIG_2(swigCPtr, this, name);
  }

  public void addSBM() {
    LinkPredJavaJNI.Evaluator_addSBM__SWIG_3(swigCPtr, this);
  }

  public void addSHP(String name, int seed) {
    LinkPredJavaJNI.Evaluator_addSHP__SWIG_0(swigCPtr, this, name, seed);
  }

  public void addSHP(String name) {
    LinkPredJavaJNI.Evaluator_addSHP__SWIG_1(swigCPtr, this, name);
  }

  public void addSHP() {
    LinkPredJavaJNI.Evaluator_addSHP__SWIG_2(swigCPtr, this);
  }

  public void addSOI(String name) {
    LinkPredJavaJNI.Evaluator_addSOI__SWIG_0(swigCPtr, this, name);
  }

  public void addSOI() {
    LinkPredJavaJNI.Evaluator_addSOI__SWIG_1(swigCPtr, this);
  }

  public void addROC() {
    LinkPredJavaJNI.Evaluator_addROC(swigCPtr, this);
  }

  public void addPR() {
    LinkPredJavaJNI.Evaluator_addPR(swigCPtr, this);
  }

  public void addTPR() {
    LinkPredJavaJNI.Evaluator_addTPR(swigCPtr, this);
  }

  public void genTestData(String fullNetFileName, String obsEdgesFileName, String remEdgesFileName, double remRatio, boolean keepConnected, int seed) {
    LinkPredJavaJNI.Evaluator_genTestData__SWIG_0(swigCPtr, this, fullNetFileName, obsEdgesFileName, remEdgesFileName, remRatio, keepConnected, seed);
  }

  public void genTestData(String fullNetFileName, String obsEdgesFileName, String remEdgesFileName, double remRatio, boolean keepConnected) {
    LinkPredJavaJNI.Evaluator_genTestData__SWIG_1(swigCPtr, this, fullNetFileName, obsEdgesFileName, remEdgesFileName, remRatio, keepConnected);
  }

  public void genTestData(String fullNetFileName, String obsEdgesFileName, String remEdgesFileName, double remRatio) {
    LinkPredJavaJNI.Evaluator_genTestData__SWIG_2(swigCPtr, this, fullNetFileName, obsEdgesFileName, remEdgesFileName, remRatio);
  }

  public void genTestData(String fullNetFileName, String obsEdgesFileName, String remEdgesFileName) {
    LinkPredJavaJNI.Evaluator_genTestData__SWIG_3(swigCPtr, this, fullNetFileName, obsEdgesFileName, remEdgesFileName);
  }

  public void run(String fullNetFileName, int nbRuns, double remRatio, boolean keepConnected, int seed) {
    LinkPredJavaJNI.Evaluator_run__SWIG_0(swigCPtr, this, fullNetFileName, nbRuns, remRatio, keepConnected, seed);
  }

  public void run(String fullNetFileName, int nbRuns, double remRatio, boolean keepConnected) {
    LinkPredJavaJNI.Evaluator_run__SWIG_1(swigCPtr, this, fullNetFileName, nbRuns, remRatio, keepConnected);
  }

  public void run(String fullNetFileName, int nbRuns, double remRatio) {
    LinkPredJavaJNI.Evaluator_run__SWIG_2(swigCPtr, this, fullNetFileName, nbRuns, remRatio);
  }

  public void run(String fullNetFileName, int nbRuns) {
    LinkPredJavaJNI.Evaluator_run__SWIG_3(swigCPtr, this, fullNetFileName, nbRuns);
  }

  public void run(String fullNetFileName) {
    LinkPredJavaJNI.Evaluator_run__SWIG_4(swigCPtr, this, fullNetFileName);
  }

  public void run(String obsEdgesFileName, String remEdgesFileName) {
    LinkPredJavaJNI.Evaluator_run__SWIG_5(swigCPtr, this, obsEdgesFileName, remEdgesFileName);
  }

  public PerfResVec getPerfRes(int iter) {
    return new PerfResVec(LinkPredJavaJNI.Evaluator_getPerfRes(swigCPtr, this, iter), true);
  }

}
