/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PerfRes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PerfRes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PerfRes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkPredJavaJNI.delete_PerfRes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    LinkPredJavaJNI.PerfRes_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return LinkPredJavaJNI.PerfRes_name_get(swigCPtr, this);
  }

  public void setRes(double value) {
    LinkPredJavaJNI.PerfRes_res_set(swigCPtr, this, value);
  }

  public double getRes() {
    return LinkPredJavaJNI.PerfRes_res_get(swigCPtr, this);
  }

  public PerfRes() {
    this(LinkPredJavaJNI.new_PerfRes(), true);
  }

}
