/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PerfResVec extends java.util.AbstractList<PerfRes> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PerfResVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PerfResVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkPredJavaJNI.delete_PerfResVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PerfResVec(PerfRes[] initialElements) {
    this();
    reserve(initialElements.length);

    for (PerfRes element : initialElements) {
      add(element);
    }
  }

  public PerfResVec(Iterable<PerfRes> initialElements) {
    this();
    for (PerfRes element : initialElements) {
      add(element);
    }
  }

  public PerfRes get(int index) {
    return doGet(index);
  }

  public PerfRes set(int index, PerfRes e) {
    return doSet(index, e);
  }

  public boolean add(PerfRes e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, PerfRes e) {
    modCount++;
    doAdd(index, e);
  }

  public PerfRes remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public PerfResVec() {
    this(LinkPredJavaJNI.new_PerfResVec__SWIG_0(), true);
  }

  public PerfResVec(PerfResVec other) {
    this(LinkPredJavaJNI.new_PerfResVec__SWIG_1(PerfResVec.getCPtr(other), other), true);
  }

  public long capacity() {
    return LinkPredJavaJNI.PerfResVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    LinkPredJavaJNI.PerfResVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return LinkPredJavaJNI.PerfResVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    LinkPredJavaJNI.PerfResVec_clear(swigCPtr, this);
  }

  public PerfResVec(int count, PerfRes value) {
    this(LinkPredJavaJNI.new_PerfResVec__SWIG_2(count, PerfRes.getCPtr(value), value), true);
  }

  private int doSize() {
    return LinkPredJavaJNI.PerfResVec_doSize(swigCPtr, this);
  }

  private void doAdd(PerfRes x) {
    LinkPredJavaJNI.PerfResVec_doAdd__SWIG_0(swigCPtr, this, PerfRes.getCPtr(x), x);
  }

  private void doAdd(int index, PerfRes x) {
    LinkPredJavaJNI.PerfResVec_doAdd__SWIG_1(swigCPtr, this, index, PerfRes.getCPtr(x), x);
  }

  private PerfRes doRemove(int index) {
    return new PerfRes(LinkPredJavaJNI.PerfResVec_doRemove(swigCPtr, this, index), true);
  }

  private PerfRes doGet(int index) {
    return new PerfRes(LinkPredJavaJNI.PerfResVec_doGet(swigCPtr, this, index), false);
  }

  private PerfRes doSet(int index, PerfRes val) {
    return new PerfRes(LinkPredJavaJNI.PerfResVec_doSet(swigCPtr, this, index, PerfRes.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    LinkPredJavaJNI.PerfResVec_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
