/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Predictor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Predictor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Predictor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkPredJavaJNI.delete_Predictor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Predictor() {
    this(LinkPredJavaJNI.new_Predictor__SWIG_0(), true);
  }

  public Predictor(Predictor that) {
    this(LinkPredJavaJNI.new_Predictor__SWIG_1(Predictor.getCPtr(that), that), true);
  }

  public int getNbNodes() {
    return LinkPredJavaJNI.Predictor_getNbNodes(swigCPtr, this);
  }

  public String getLabel(int i) {
    return LinkPredJavaJNI.Predictor_getLabel(swigCPtr, this, i);
  }

  public int getID(String i) {
    return LinkPredJavaJNI.Predictor_getID(swigCPtr, this, i);
  }

  public boolean isEdgeByID(int i, int j) {
    return LinkPredJavaJNI.Predictor_isEdgeByID(swigCPtr, this, i, j);
  }

  public boolean isEdgeByLabel(String i, String j) {
    return LinkPredJavaJNI.Predictor_isEdgeByLabel(swigCPtr, this, i, j);
  }

  public void loadnet(String fileName) {
    LinkPredJavaJNI.Predictor_loadnet(swigCPtr, this, fileName);
  }

  public EdgeScoreVec predAllADA() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllADA(swigCPtr, this), true);
  }

  public void predADA(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predADA(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopADA(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopADA(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllCNE() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllCNE(swigCPtr, this), true);
  }

  public void predCNE(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predCNE(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopCNE(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopCNE(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllCRA() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllCRA(swigCPtr, this), true);
  }

  public void predCRA(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predCRA(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopCRA(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopCRA(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllECL(String encoderName, String classifierName, int dim, double posRatio, double negRatio, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllECL__SWIG_0(swigCPtr, this, encoderName, classifierName, dim, posRatio, negRatio, seed), true);
  }

  public EdgeScoreVec predAllECL(String encoderName, String classifierName, int dim, double posRatio, double negRatio) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllECL__SWIG_1(swigCPtr, this, encoderName, classifierName, dim, posRatio, negRatio), true);
  }

  public EdgeScoreVec predAllECL(String encoderName, String classifierName, int dim, double posRatio) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllECL__SWIG_2(swigCPtr, this, encoderName, classifierName, dim, posRatio), true);
  }

  public EdgeScoreVec predAllECL(String encoderName, String classifierName, int dim) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllECL__SWIG_3(swigCPtr, this, encoderName, classifierName, dim), true);
  }

  public EdgeScoreVec predAllECL(String encoderName, String classifierName) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllECL__SWIG_4(swigCPtr, this, encoderName, classifierName), true);
  }

  public EdgeScoreVec predAllECL(String encoderName) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllECL__SWIG_5(swigCPtr, this, encoderName), true);
  }

  public EdgeScoreVec predAllECL() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllECL__SWIG_6(swigCPtr, this), true);
  }

  public void predECL(EdgeScoreVec edgeScores, String encoderName, String classifierName, int dim, double posRatio, double negRatio, int seed) {
    LinkPredJavaJNI.Predictor_predECL__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName, classifierName, dim, posRatio, negRatio, seed);
  }

  public void predECL(EdgeScoreVec edgeScores, String encoderName, String classifierName, int dim, double posRatio, double negRatio) {
    LinkPredJavaJNI.Predictor_predECL__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName, classifierName, dim, posRatio, negRatio);
  }

  public void predECL(EdgeScoreVec edgeScores, String encoderName, String classifierName, int dim, double posRatio) {
    LinkPredJavaJNI.Predictor_predECL__SWIG_2(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName, classifierName, dim, posRatio);
  }

  public void predECL(EdgeScoreVec edgeScores, String encoderName, String classifierName, int dim) {
    LinkPredJavaJNI.Predictor_predECL__SWIG_3(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName, classifierName, dim);
  }

  public void predECL(EdgeScoreVec edgeScores, String encoderName, String classifierName) {
    LinkPredJavaJNI.Predictor_predECL__SWIG_4(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName, classifierName);
  }

  public void predECL(EdgeScoreVec edgeScores, String encoderName) {
    LinkPredJavaJNI.Predictor_predECL__SWIG_5(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName);
  }

  public void predECL(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predECL__SWIG_6(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopECL(int k, String encoderName, String classifierName, int dim, double posRatio, double negRatio, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopECL__SWIG_0(swigCPtr, this, k, encoderName, classifierName, dim, posRatio, negRatio, seed), true);
  }

  public EdgeScoreVec predTopECL(int k, String encoderName, String classifierName, int dim, double posRatio, double negRatio) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopECL__SWIG_1(swigCPtr, this, k, encoderName, classifierName, dim, posRatio, negRatio), true);
  }

  public EdgeScoreVec predTopECL(int k, String encoderName, String classifierName, int dim, double posRatio) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopECL__SWIG_2(swigCPtr, this, k, encoderName, classifierName, dim, posRatio), true);
  }

  public EdgeScoreVec predTopECL(int k, String encoderName, String classifierName, int dim) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopECL__SWIG_3(swigCPtr, this, k, encoderName, classifierName, dim), true);
  }

  public EdgeScoreVec predTopECL(int k, String encoderName, String classifierName) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopECL__SWIG_4(swigCPtr, this, k, encoderName, classifierName), true);
  }

  public EdgeScoreVec predTopECL(int k, String encoderName) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopECL__SWIG_5(swigCPtr, this, k, encoderName), true);
  }

  public EdgeScoreVec predTopECL(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopECL__SWIG_6(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllESM(String encoderName, String simMeasureName, int dim, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllESM__SWIG_0(swigCPtr, this, encoderName, simMeasureName, dim, seed), true);
  }

  public EdgeScoreVec predAllESM(String encoderName, String simMeasureName, int dim) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllESM__SWIG_1(swigCPtr, this, encoderName, simMeasureName, dim), true);
  }

  public EdgeScoreVec predAllESM(String encoderName, String simMeasureName) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllESM__SWIG_2(swigCPtr, this, encoderName, simMeasureName), true);
  }

  public EdgeScoreVec predAllESM(String encoderName) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllESM__SWIG_3(swigCPtr, this, encoderName), true);
  }

  public EdgeScoreVec predAllESM() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllESM__SWIG_4(swigCPtr, this), true);
  }

  public void predESM(EdgeScoreVec edgeScores, String encoderName, String simMeasureName, int dim, int seed) {
    LinkPredJavaJNI.Predictor_predESM__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName, simMeasureName, dim, seed);
  }

  public void predESM(EdgeScoreVec edgeScores, String encoderName, String simMeasureName, int dim) {
    LinkPredJavaJNI.Predictor_predESM__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName, simMeasureName, dim);
  }

  public void predESM(EdgeScoreVec edgeScores, String encoderName, String simMeasureName) {
    LinkPredJavaJNI.Predictor_predESM__SWIG_2(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName, simMeasureName);
  }

  public void predESM(EdgeScoreVec edgeScores, String encoderName) {
    LinkPredJavaJNI.Predictor_predESM__SWIG_3(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, encoderName);
  }

  public void predESM(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predESM__SWIG_4(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopESM(int k, String encoderName, String simMeasureName, int dim, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopESM__SWIG_0(swigCPtr, this, k, encoderName, simMeasureName, dim, seed), true);
  }

  public EdgeScoreVec predTopESM(int k, String encoderName, String simMeasureName, int dim) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopESM__SWIG_1(swigCPtr, this, k, encoderName, simMeasureName, dim), true);
  }

  public EdgeScoreVec predTopESM(int k, String encoderName, String simMeasureName) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopESM__SWIG_2(swigCPtr, this, k, encoderName, simMeasureName), true);
  }

  public EdgeScoreVec predTopESM(int k, String encoderName) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopESM__SWIG_3(swigCPtr, this, k, encoderName), true);
  }

  public EdgeScoreVec predTopESM(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopESM__SWIG_4(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllFBM(int maxIter, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllFBM__SWIG_0(swigCPtr, this, maxIter, seed), true);
  }

  public EdgeScoreVec predAllFBM(int maxIter) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllFBM__SWIG_1(swigCPtr, this, maxIter), true);
  }

  public EdgeScoreVec predAllFBM() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllFBM__SWIG_2(swigCPtr, this), true);
  }

  public void predFBM(EdgeScoreVec edgeScores, int maxIter, int seed) {
    LinkPredJavaJNI.Predictor_predFBM__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, maxIter, seed);
  }

  public void predFBM(EdgeScoreVec edgeScores, int maxIter) {
    LinkPredJavaJNI.Predictor_predFBM__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, maxIter);
  }

  public void predFBM(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predFBM__SWIG_2(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopFBM(int k, int maxIter, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopFBM__SWIG_0(swigCPtr, this, k, maxIter, seed), true);
  }

  public EdgeScoreVec predTopFBM(int k, int maxIter) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopFBM__SWIG_1(swigCPtr, this, k, maxIter), true);
  }

  public EdgeScoreVec predTopFBM(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopFBM__SWIG_2(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllHDI() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHDI(swigCPtr, this), true);
  }

  public void predHDI(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predHDI(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopHDI(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHDI(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllHPI() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHPI(swigCPtr, this), true);
  }

  public void predHPI(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predHPI(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopHPI(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHPI(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllHRG(int nbBeans, int nbSamples, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHRG__SWIG_0(swigCPtr, this, nbBeans, nbSamples, seed), true);
  }

  public EdgeScoreVec predAllHRG(int nbBeans, int nbSamples) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHRG__SWIG_1(swigCPtr, this, nbBeans, nbSamples), true);
  }

  public EdgeScoreVec predAllHRG(int nbBeans) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHRG__SWIG_2(swigCPtr, this, nbBeans), true);
  }

  public EdgeScoreVec predAllHRG() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHRG__SWIG_3(swigCPtr, this), true);
  }

  public void predHRG(EdgeScoreVec edgeScores, int nbBeans, int nbSamples, int seed) {
    LinkPredJavaJNI.Predictor_predHRG__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, nbBeans, nbSamples, seed);
  }

  public void predHRG(EdgeScoreVec edgeScores, int nbBeans, int nbSamples) {
    LinkPredJavaJNI.Predictor_predHRG__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, nbBeans, nbSamples);
  }

  public void predHRG(EdgeScoreVec edgeScores, int nbBeans) {
    LinkPredJavaJNI.Predictor_predHRG__SWIG_2(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, nbBeans);
  }

  public void predHRG(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predHRG__SWIG_3(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopHRG(int k, int nbBeans, int nbSamples, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHRG__SWIG_0(swigCPtr, this, k, nbBeans, nbSamples, seed), true);
  }

  public EdgeScoreVec predTopHRG(int k, int nbBeans, int nbSamples) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHRG__SWIG_1(swigCPtr, this, k, nbBeans, nbSamples), true);
  }

  public EdgeScoreVec predTopHRG(int k, int nbBeans) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHRG__SWIG_2(swigCPtr, this, k, nbBeans), true);
  }

  public EdgeScoreVec predTopHRG(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHRG__SWIG_3(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllHYP(double m, double L, double gamma, double zeta, double T, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHYP__SWIG_0(swigCPtr, this, m, L, gamma, zeta, T, seed), true);
  }

  public EdgeScoreVec predAllHYP(double m, double L, double gamma, double zeta, double T) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHYP__SWIG_1(swigCPtr, this, m, L, gamma, zeta, T), true);
  }

  public EdgeScoreVec predAllHYP(double m, double L, double gamma, double zeta) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHYP__SWIG_2(swigCPtr, this, m, L, gamma, zeta), true);
  }

  public EdgeScoreVec predAllHYP(double m, double L, double gamma) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHYP__SWIG_3(swigCPtr, this, m, L, gamma), true);
  }

  public EdgeScoreVec predAllHYP(double m, double L) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHYP__SWIG_4(swigCPtr, this, m, L), true);
  }

  public EdgeScoreVec predAllHYP(double m) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHYP__SWIG_5(swigCPtr, this, m), true);
  }

  public EdgeScoreVec predAllHYP() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllHYP__SWIG_6(swigCPtr, this), true);
  }

  public void predHYP(EdgeScoreVec edgeScores, double m, double L, double gamma, double zeta, double T, int seed) {
    LinkPredJavaJNI.Predictor_predHYP__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, m, L, gamma, zeta, T, seed);
  }

  public void predHYP(EdgeScoreVec edgeScores, double m, double L, double gamma, double zeta, double T) {
    LinkPredJavaJNI.Predictor_predHYP__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, m, L, gamma, zeta, T);
  }

  public void predHYP(EdgeScoreVec edgeScores, double m, double L, double gamma, double zeta) {
    LinkPredJavaJNI.Predictor_predHYP__SWIG_2(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, m, L, gamma, zeta);
  }

  public void predHYP(EdgeScoreVec edgeScores, double m, double L, double gamma) {
    LinkPredJavaJNI.Predictor_predHYP__SWIG_3(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, m, L, gamma);
  }

  public void predHYP(EdgeScoreVec edgeScores, double m, double L) {
    LinkPredJavaJNI.Predictor_predHYP__SWIG_4(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, m, L);
  }

  public void predHYP(EdgeScoreVec edgeScores, double m) {
    LinkPredJavaJNI.Predictor_predHYP__SWIG_5(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, m);
  }

  public void predHYP(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predHYP__SWIG_6(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopHYP(int k, double m, double L, double gamma, double zeta, double T, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHYP__SWIG_0(swigCPtr, this, k, m, L, gamma, zeta, T, seed), true);
  }

  public EdgeScoreVec predTopHYP(int k, double m, double L, double gamma, double zeta, double T) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHYP__SWIG_1(swigCPtr, this, k, m, L, gamma, zeta, T), true);
  }

  public EdgeScoreVec predTopHYP(int k, double m, double L, double gamma, double zeta) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHYP__SWIG_2(swigCPtr, this, k, m, L, gamma, zeta), true);
  }

  public EdgeScoreVec predTopHYP(int k, double m, double L, double gamma) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHYP__SWIG_3(swigCPtr, this, k, m, L, gamma), true);
  }

  public EdgeScoreVec predTopHYP(int k, double m, double L) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHYP__SWIG_4(swigCPtr, this, k, m, L), true);
  }

  public EdgeScoreVec predTopHYP(int k, double m) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHYP__SWIG_5(swigCPtr, this, k, m), true);
  }

  public EdgeScoreVec predTopHYP(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopHYP__SWIG_6(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllJID() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllJID(swigCPtr, this), true);
  }

  public void predJID(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predJID(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopJID(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopJID(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllKAB(int horizLim) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllKAB__SWIG_0(swigCPtr, this, horizLim), true);
  }

  public EdgeScoreVec predAllKAB() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllKAB__SWIG_1(swigCPtr, this), true);
  }

  public void predKAB(EdgeScoreVec edgeScores, int horizLim) {
    LinkPredJavaJNI.Predictor_predKAB__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, horizLim);
  }

  public void predKAB(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predKAB__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopKAB(int k, int horizLim) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopKAB__SWIG_0(swigCPtr, this, k, horizLim), true);
  }

  public EdgeScoreVec predTopKAB(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopKAB__SWIG_1(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllLCP(double epsilon) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllLCP__SWIG_0(swigCPtr, this, epsilon), true);
  }

  public EdgeScoreVec predAllLCP() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllLCP__SWIG_1(swigCPtr, this), true);
  }

  public void predLCP(EdgeScoreVec edgeScores, double epsilon) {
    LinkPredJavaJNI.Predictor_predLCP__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, epsilon);
  }

  public void predLCP(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predLCP__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopLCP(int k, double epsilon) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopLCP__SWIG_0(swigCPtr, this, k, epsilon), true);
  }

  public EdgeScoreVec predTopLCP(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopLCP__SWIG_1(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllLHN() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllLHN(swigCPtr, this), true);
  }

  public void predLHN(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predLHN(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopLHN(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopLHN(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllPAT() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllPAT(swigCPtr, this), true);
  }

  public void predPAT(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predPAT(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopPAT(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopPAT(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllRAL() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllRAL(swigCPtr, this), true);
  }

  public void predRAL(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predRAL(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopRAL(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopRAL(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllRND(int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllRND__SWIG_0(swigCPtr, this, seed), true);
  }

  public EdgeScoreVec predAllRND() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllRND__SWIG_1(swigCPtr, this), true);
  }

  public void predRND(EdgeScoreVec edgeScores, int seed) {
    LinkPredJavaJNI.Predictor_predRND__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, seed);
  }

  public void predRND(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predRND__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopRND(int k, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopRND__SWIG_0(swigCPtr, this, k, seed), true);
  }

  public EdgeScoreVec predTopRND(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopRND__SWIG_1(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllSAI() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllSAI(swigCPtr, this), true);
  }

  public void predSAI(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predSAI(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopSAI(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopSAI(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllSBM(int maxIter, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllSBM__SWIG_0(swigCPtr, this, maxIter, seed), true);
  }

  public EdgeScoreVec predAllSBM(int maxIter) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllSBM__SWIG_1(swigCPtr, this, maxIter), true);
  }

  public EdgeScoreVec predAllSBM() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllSBM__SWIG_2(swigCPtr, this), true);
  }

  public void predSBM(EdgeScoreVec edgeScores, int maxIter, int seed) {
    LinkPredJavaJNI.Predictor_predSBM__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, maxIter, seed);
  }

  public void predSBM(EdgeScoreVec edgeScores, int maxIter) {
    LinkPredJavaJNI.Predictor_predSBM__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, maxIter);
  }

  public void predSBM(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predSBM__SWIG_2(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopSBM(int k, int maxIter, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopSBM__SWIG_0(swigCPtr, this, k, maxIter, seed), true);
  }

  public EdgeScoreVec predTopSBM(int k, int maxIter) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopSBM__SWIG_1(swigCPtr, this, k, maxIter), true);
  }

  public EdgeScoreVec predTopSBM(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopSBM__SWIG_2(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllSHP(int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllSHP__SWIG_0(swigCPtr, this, seed), true);
  }

  public EdgeScoreVec predAllSHP() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllSHP__SWIG_1(swigCPtr, this), true);
  }

  public void predSHP(EdgeScoreVec edgeScores, int seed) {
    LinkPredJavaJNI.Predictor_predSHP__SWIG_0(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores, seed);
  }

  public void predSHP(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predSHP__SWIG_1(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopSHP(int k, int seed) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopSHP__SWIG_0(swigCPtr, this, k, seed), true);
  }

  public EdgeScoreVec predTopSHP(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopSHP__SWIG_1(swigCPtr, this, k), true);
  }

  public EdgeScoreVec predAllSOI() {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predAllSOI(swigCPtr, this), true);
  }

  public void predSOI(EdgeScoreVec edgeScores) {
    LinkPredJavaJNI.Predictor_predSOI(swigCPtr, this, EdgeScoreVec.getCPtr(edgeScores), edgeScores);
  }

  public EdgeScoreVec predTopSOI(int k) {
    return new EdgeScoreVec(LinkPredJavaJNI.Predictor_predTopSOI(swigCPtr, this, k), true);
  }

  public EdgeScoreByIDVec predAllADAByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllADAByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllCNEByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllCNEByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllCRAByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllCRAByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllECLByID(String encoderName, String classifierName, int dim, double posRatio, double negRatio, int seed) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllECLByID__SWIG_0(swigCPtr, this, encoderName, classifierName, dim, posRatio, negRatio, seed), true);
  }

  public EdgeScoreByIDVec predAllECLByID(String encoderName, String classifierName, int dim, double posRatio, double negRatio) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllECLByID__SWIG_1(swigCPtr, this, encoderName, classifierName, dim, posRatio, negRatio), true);
  }

  public EdgeScoreByIDVec predAllECLByID(String encoderName, String classifierName, int dim, double posRatio) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllECLByID__SWIG_2(swigCPtr, this, encoderName, classifierName, dim, posRatio), true);
  }

  public EdgeScoreByIDVec predAllECLByID(String encoderName, String classifierName, int dim) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllECLByID__SWIG_3(swigCPtr, this, encoderName, classifierName, dim), true);
  }

  public EdgeScoreByIDVec predAllECLByID(String encoderName, String classifierName) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllECLByID__SWIG_4(swigCPtr, this, encoderName, classifierName), true);
  }

  public EdgeScoreByIDVec predAllECLByID(String encoderName) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllECLByID__SWIG_5(swigCPtr, this, encoderName), true);
  }

  public EdgeScoreByIDVec predAllECLByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllECLByID__SWIG_6(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllESMByID(String encoderName, String simMeasureName, int dim, int seed) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllESMByID__SWIG_0(swigCPtr, this, encoderName, simMeasureName, dim, seed), true);
  }

  public EdgeScoreByIDVec predAllESMByID(String encoderName, String simMeasureName, int dim) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllESMByID__SWIG_1(swigCPtr, this, encoderName, simMeasureName, dim), true);
  }

  public EdgeScoreByIDVec predAllESMByID(String encoderName, String simMeasureName) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllESMByID__SWIG_2(swigCPtr, this, encoderName, simMeasureName), true);
  }

  public EdgeScoreByIDVec predAllESMByID(String encoderName) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllESMByID__SWIG_3(swigCPtr, this, encoderName), true);
  }

  public EdgeScoreByIDVec predAllESMByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllESMByID__SWIG_4(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllFBMByID(int maxIter, int seed) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllFBMByID__SWIG_0(swigCPtr, this, maxIter, seed), true);
  }

  public EdgeScoreByIDVec predAllFBMByID(int maxIter) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllFBMByID__SWIG_1(swigCPtr, this, maxIter), true);
  }

  public EdgeScoreByIDVec predAllFBMByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllFBMByID__SWIG_2(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllHDIByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHDIByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllHPIByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHPIByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllHRGByID(int nbBeans, int nbSamples, int seed) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHRGByID__SWIG_0(swigCPtr, this, nbBeans, nbSamples, seed), true);
  }

  public EdgeScoreByIDVec predAllHRGByID(int nbBeans, int nbSamples) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHRGByID__SWIG_1(swigCPtr, this, nbBeans, nbSamples), true);
  }

  public EdgeScoreByIDVec predAllHRGByID(int nbBeans) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHRGByID__SWIG_2(swigCPtr, this, nbBeans), true);
  }

  public EdgeScoreByIDVec predAllHRGByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHRGByID__SWIG_3(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllHYPByID(double m, double L, double gamma, double zeta, double T, int seed) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHYPByID__SWIG_0(swigCPtr, this, m, L, gamma, zeta, T, seed), true);
  }

  public EdgeScoreByIDVec predAllHYPByID(double m, double L, double gamma, double zeta, double T) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHYPByID__SWIG_1(swigCPtr, this, m, L, gamma, zeta, T), true);
  }

  public EdgeScoreByIDVec predAllHYPByID(double m, double L, double gamma, double zeta) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHYPByID__SWIG_2(swigCPtr, this, m, L, gamma, zeta), true);
  }

  public EdgeScoreByIDVec predAllHYPByID(double m, double L, double gamma) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHYPByID__SWIG_3(swigCPtr, this, m, L, gamma), true);
  }

  public EdgeScoreByIDVec predAllHYPByID(double m, double L) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHYPByID__SWIG_4(swigCPtr, this, m, L), true);
  }

  public EdgeScoreByIDVec predAllHYPByID(double m) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHYPByID__SWIG_5(swigCPtr, this, m), true);
  }

  public EdgeScoreByIDVec predAllHYPByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllHYPByID__SWIG_6(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllJIDByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllJIDByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllKABByID(int horizLim) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllKABByID__SWIG_0(swigCPtr, this, horizLim), true);
  }

  public EdgeScoreByIDVec predAllKABByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllKABByID__SWIG_1(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllLCPByID(double epsilon) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllLCPByID__SWIG_0(swigCPtr, this, epsilon), true);
  }

  public EdgeScoreByIDVec predAllLCPByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllLCPByID__SWIG_1(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllLHNByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllLHNByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllPATByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllPATByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllRALByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllRALByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllRNDByID(int seed) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllRNDByID__SWIG_0(swigCPtr, this, seed), true);
  }

  public EdgeScoreByIDVec predAllRNDByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllRNDByID__SWIG_1(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllSAIByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllSAIByID(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllSBMByID(int maxIter, int seed) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllSBMByID__SWIG_0(swigCPtr, this, maxIter, seed), true);
  }

  public EdgeScoreByIDVec predAllSBMByID(int maxIter) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllSBMByID__SWIG_1(swigCPtr, this, maxIter), true);
  }

  public EdgeScoreByIDVec predAllSBMByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllSBMByID__SWIG_2(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllSHPByID(int seed) {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllSHPByID__SWIG_0(swigCPtr, this, seed), true);
  }

  public EdgeScoreByIDVec predAllSHPByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllSHPByID__SWIG_1(swigCPtr, this), true);
  }

  public EdgeScoreByIDVec predAllSOIByID() {
    return new EdgeScoreByIDVec(LinkPredJavaJNI.Predictor_predAllSOIByID(swigCPtr, this), true);
  }

}
